// RisBo.js — zero-dependency bundler.
// Inlines the ES modules in src/ into two self-contained files:
//   dist/risbo.js         — a single-file ES module (for bundlers / <script type=module>)
//   dist/risbo.global.js  — an IIFE that sets window.RisBo (for plain <script> / CDN)
//
// It wraps each module in a CommonJS-style factory and a tiny runtime require,
// which keeps the transform simple and robust for this small, well-behaved
// module graph. `npm run build` then `npm test` (prepublish) verifies output.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src");
const dist = join(root, "dist");

const MODULES = ["reactivity", "dom", "server", "router", "store", "index"];
const idOf = (path) => path.replace(/^.*\//, "").replace(/\.js$/, "");

/** Transform one module's source into a factory body + its export names. */
function transform(code) {
  const names = new Set();
  const assignments = [];
  let tmp = 0;

  // 1) export { a, b as c } from "./mod.js";
  code = code.replace(
    /export\s*{([^}]*)}\s*from\s*["']([^"']+)["'];?/g,
    (_, specs, path) => {
      const local = `__re${tmp++}`;
      const lines = [`const ${local} = __require("${idOf(path)}");`];
      for (const spec of splitSpecs(specs)) {
        names.add(spec.exported);
        lines.push(`exports.${spec.exported} = ${local}.${spec.local};`);
      }
      return lines.join("\n");
    }
  );

  // 2) import * as ns from "./mod.js";
  code = code.replace(
    /import\s+\*\s+as\s+([A-Za-z0-9_$]+)\s+from\s*["']([^"']+)["'];?/g,
    (_, ns, path) => `const ${ns} = __require("${idOf(path)}");`
  );

  // 3) import { a, b as c } from "./mod.js";
  code = code.replace(
    /import\s*{([^}]*)}\s*from\s*["']([^"']+)["'];?/g,
    (_, specs, path) => {
      const parts = splitSpecs(specs).map((s) => (s.local === s.exported ? s.exported : `${s.exported}: ${s.local}`));
      return `const { ${parts.join(", ")} } = __require("${idOf(path)}");`;
    }
  );

  // 4) import Default from "./mod.js";
  code = code.replace(
    /import\s+([A-Za-z0-9_$]+)\s+from\s*["']([^"']+)["'];?/g,
    (_, name, path) => `const ${name} = __require("${idOf(path)}").default;`
  );

  // 5) export default EXPR;
  code = code.replace(/export\s+default\s+([^;]+);/g, (_, expr) => {
    names.add("default");
    return `exports.default = ${expr};`;
  });

  // 6) export function/const/let/class NAME
  code = code.replace(/export\s+function\s+([A-Za-z0-9_$]+)/g, (_, name) => {
    names.add(name);
    assignments.push(name);
    return `function ${name}`;
  });
  code = code.replace(/export\s+(const|let|class)\s+([A-Za-z0-9_$]+)/g, (_, kw, name) => {
    names.add(name);
    assignments.push(name);
    return `${kw} ${name}`;
  });

  // 7) export { a, b as c };  (no "from" — locals already declared above)
  code = code.replace(/export\s*{([^}]*)}\s*;?/g, (_, specs) => {
    for (const spec of splitSpecs(specs)) {
      names.add(spec.exported);
      assignments.push([spec.exported, spec.local]);
    }
    return "";
  });

  const tail = assignments
    .map((a) => (Array.isArray(a) ? `exports.${a[0]} = ${a[1]};` : `exports.${a} = ${a};`))
    .join("\n");

  return { code: `${code}\n${tail}`, names };
}

function splitSpecs(specs) {
  return specs
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean)
    .map((s) => {
      const m = s.split(/\s+as\s+/);
      return { local: m[0].trim(), exported: (m[1] || m[0]).trim() };
    });
}

// ---- assemble ----
const runtime = `var __mods = {}, __cache = {};
function __def(id, fn) { __mods[id] = fn; }
function __require(id) {
  if (__cache[id]) return __cache[id].exports;
  var module = __cache[id] = { exports: {} };
  __mods[id](module, module.exports, __require);
  return module.exports;
}`;

let defs = "";
let entryNames = [];
for (const id of MODULES) {
  const source = readFileSync(join(src, `${id}.js`), "utf8");
  const { code, names } = transform(source);
  defs += `\n__def("${id}", function(module, exports, __require) {\n${code}\n});\n`;
  if (id === "index") entryNames = [...names];
}

const named = entryNames.filter((n) => n !== "default");

const esm = `// RisBo.js v${getVersion()} — bundled ES module. Generated by scripts/build.js.
${runtime}
${defs}
var __risbo = __require("index");
${named.map((n) => `export var ${n} = __risbo.${n};`).join("\n")}
export default __risbo.default;
`;

const global = `// RisBo.js v${getVersion()} — global build. Generated by scripts/build.js.
(function (global) {
${runtime}
${defs}
global.RisBo = __require("index");
})(typeof globalThis !== "undefined" ? globalThis : this);
`;

mkdirSync(dist, { recursive: true });
writeFileSync(join(dist, "risbo.js"), esm);
writeFileSync(join(dist, "risbo.global.js"), global);

const kb = (s) => (Buffer.byteLength(s) / 1024).toFixed(1) + " kB";
console.log("built dist/risbo.js        " + kb(esm) + `  (${named.length} named exports)`);
console.log("built dist/risbo.global.js " + kb(global));

function getVersion() {
  return JSON.parse(readFileSync(join(root, "package.json"), "utf8")).version;
}
